
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.3'

use_frameworks!

target 'ISS Pager' do
    
    pod 'Alamofire', '~> 4.0'
    pod 'Moya', '8.0.0-beta.6'

    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |configuration|
            configuration.build_settings['SWIFT_VERSION'] = "3.0"
        end
    end
end
